### ISSUE TITLE
Do you still use this? or is it broken?

### ISSUE THREAD

**Issue by gth001** [heston/label-commander#13] opened 2022-01-02 19:50 UTC

**Comment by heston** [comment] 2022-04-27 19:40
I use it all the time. Are you running into an issue?

**Comment by gth001** [comment] 2022-04-27 21:25
Thanks for confirming. This sounds super useful. I gave up on getting it working earlier in the year, but my issue is probably between the keyboard and the chair. I just wanted to know it wasn't a dead end, before I sunk too many hours into learning how to use firebase. I'll give it another shot.

**Comment by heston** [comment] 2022-04-27 21:52
Some of the dependencies are out of date, since I haven't added anything new to the project in a while. However, I can confirm that it does work!

**Comment by heston** [comment] 2022-05-18 15:31
I just merged several updates, and have confirmed that I can get a new installation running just fine.

**Closed as completed by heston** 2022-05-18 15:31 UTC
